### ISSUE TITLE
Better questing error.

### ISSUE THREAD

**Issue by Zebrix** [m2r1k5/nomi-ceu#10]
There are problems with quests when trying to start the server. The first launch leads to a crash, and the second one launches with an empty database. An attempt to load the default by an command also only reports an error
[crash-2022-02-14_12.15.50-server.txt.zip](https://github.com/m2r1k5/nomi-ceu/files/8058057/crash-2022-02-14_12.15.50-server.txt.zip)
p.s. ver 0.6

**Comment by m2r1k5** [comment]
Closing for now, if this issue re-occurs do reopen this
