### ISSUE TITLE
wrong thermal expansion augument recipe.

### ISSUE THREAD

**Issue by azutake** [m2r1k5/nomi-ceu#12]
Version: 0.6.1-beta

![image](https://user-images.githubusercontent.com/5910976/155529470-53b41f47-c274-4aa4-ba38-60510acf1e56.png)

Ender IO's Conductive Iron Block doesn't have a recipe to create.
Isn't it a mistake in `Block of Conductive Iron` (GregTech) ?

**Comment by m2r1k5** [comment]
Resolved with version 0.7-beta
