### ISSUE TITLE
Multi-smelter quest asks for too many heat proof casings

### ISSUE THREAD

**Issue by BronsonMagnan** [m2r1k5/nomi-ceu#19]
**Pack Version:**
1.01a

**Description:**
Quest for multi-smelter is misleading, asks for too many heat proof casings. This is because maintenance hatch and muffler hatch are not accounted for.

**Expected Behavior:**
Should ask for 12 Heat proof casings in retrieval task. 
Quest text should be altered to mention maintenance and muffler hatches, along side the 8 coil blocks, 1 input bus, 1 output bus, and at least 1 energy input hatch of any tier.

**Steps To Reproduce:**
Open Quest

**Screenshots:**

**Comment by m2r1k5** [comment]
I can't account for the maintenance and muffler hatches, because you can use any type of them in the multiblock. Instead I mentioned it in one of the information quests.
But I will change the quest info and tasks
