### ISSUE TITLE
Ores Have No Texture.

### ISSUE THREAD

**Issue by be1rad** [m2r1k5/nomi-ceu#361]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

Prism Launchear

### Configurations or Mods Changed

Add IGBLONs Resource Pack

### Environment

SinglePlayer

### Mode

Normal Mode

### What Happened

Ores have a black and purple texture.

### Expected Behavior

Ores Textures Should Get Generated(Or Something) And Show Up In The Game.

### Reproduction Steps

1. Download IGBLONs Resource Pack.
2. Enable It.
3. Try Looking For Ores.

### Additional Information

When I Do The Same On CF / Mojang Launcher, It Works Fine.

**Comment by Folanlron** [comment]
This is a issue with the Texture pack creator, we have nothing to do with those..
